[package]
name = "flight-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-time = "0.12.1"
flight-builder-macros = { path = "flight-builder-macros" }
hashbrown = { version = "0.15.2" }

[dev-dependencies]
rand = "0.9.0"


[features]
default = ["std"]
std = []
