name: Crate Coverage Test

on:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install llvm
        run: cargo +stable install cargo-llvm-cov --locked

      - name: Coverage
        run: ./coverage.sh
